name: Lint and test

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Pull docker image 🐳
        run: docker pull riga/law

      - name: Lint 🔍
        run: ./tests/docker.sh riga/law ./tests/lint.sh

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies ☕️
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Check bundling 📦
        run: python setup.py sdist

      - name: Check setup 🚦
        run: twine check "dist/$( python setup.py --fullname ).tar.gz"

  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - {python: "37", os: ubuntu-22.04}
          - {python: "38", os: ubuntu-latest}
          - {python: "39", os: ubuntu-latest}
          - {python: "310", os: ubuntu-latest}
          - {python: "311", os: ubuntu-latest}
          - {python: "312", os: ubuntu-latest}
          - {python: "313", os: ubuntu-latest}
    runs-on: ${{ matrix.version.os }}
    name: test (python ${{ matrix.version.python }})
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Pull docker image 🐳
        run: docker pull riga/law:py${{ matrix.version.python }}

      - name: Test 🎢
        run: ./tests/docker.sh riga/law:py${{ matrix.version.python }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Pull docker image 🐳
        run: docker pull riga/law

      - name: Run coverage test 🎢
        run: ./tests/docker.sh riga/law ./tests/coverage.sh

      - name: Upload report 🔝
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
